export enum ErrorCode {
  ERROR_DEFAULT = 1,
  INVALID_REQUEST = 2,
  RESOURCE_NOT_FOUND = 3,
  VALIDATION_DEFAULT = 1000,
  VALIDATION_TAB_CREATION_INSTRUCTIONS_MISSING = 1001,
  VALIDATION_TAB_CREATION_INSTRUCTIONS_INVALID_TYPE = 1002,
  VALIDATION_TAB_CREATION_INSTRUCTIONS_EMPTY_VALUE = 1003,
  VALIDATION_TAB_CREATION_ROWS_QUANTITY_MISSING = 1004,
  VALIDATION_TAB_CREATION_ROWS_QUANTITY_INVALID_VALUE = 1005,
  VALIDATION_TAB_CREATION_ROWS_SPACING_MISSING = 1006,
  VALIDATION_TAB_CREATION_ROWS_SPACING_INVALID_VALUE = 1007,
}
