export enum ErrorCode {
  VALIDATION_DEFAULT = 2001,
  VALIDATION_REQUIRED_PARAMETER_MISSING = 2002,
  VALIDATION_REQUIRED_PARAMETER_EMPTY = 2003,
  VALIDATION_INVALID_TYPE = 2004,
  VALIDATION_INVALID_INT_RANGE_VALUE = 2005,
  UNPROCESSABLE_TAB_INSTRUCTION = 3001,
}
